import 'package:flutter/material.dart';

class GameField {
  const GameField({
    required this.n,
    required this.name,
    required this.subtitle,
    required this.color,
    required this.intro,
    required this.task,
  });

  final int n;
  final String name;
  final String subtitle;
  final Color color;
  final String intro;
  final String task;

  String get paddedNumber => n.toString().padLeft(2, '0');
}

const List<GameField> kFields = [
  GameField(n: 1,  name: 'IDEA & BEGINNING',  subtitle: 'The First Spark',
    color: Color(0xFFE8D9A0),
    intro: '🌟 Everything starts with an idea. And here it is — your request.',
    task: 'What exactly ignites you in this desire?'),
  GameField(n: 2,  name: 'WISDOM',            subtitle: 'Vital Flow',
    color: Color(0xFFA6BFDE),
    intro: '🧠 Recall the moment when you first thought of your desire.',
    task: 'Describe that state.'),
  GameField(n: 3,  name: 'FORM',              subtitle: 'The Shape of Intention',
    color: Color(0xFFB8404E),
    intro: '🎨 For a desire to manifest, it needs a form.',
    task: 'Describe the ideal version of realization.'),
  GameField(n: 4,  name: 'MERCY',             subtitle: 'The Open Heart',
    color: Color(0xFF5E4380),
    intro: '🤲 What do you give to the world in return?',
    task: 'What are you already giving?'),
  GameField(n: 5,  name: 'LIMITATIONS',       subtitle: 'The Gift of Edges',
    color: Color(0xFFD88438),
    intro: '🧱 All desires pass through trials.',
    task: 'Write out your limitations.'),
  GameField(n: 6,  name: 'BEAUTY',            subtitle: 'The Path of Self-Love',
    color: Color(0xFFE5B5C2),
    intro: '💖 Beauty — the path through self-love.',
    task: 'Who are you? Who were you as a child? Who do you want to become?'),
  GameField(n: 7,  name: 'VICTORY',           subtitle: 'The Quiet Triumph',
    color: Color(0xFFC8843E),
    intro: '🏆 Victory over yourself gives strength.',
    task: 'What feeling is driving you right now?'),
  GameField(n: 8,  name: 'CONSCIOUSNESS',     subtitle: 'The Awakened Eye',
    color: Color(0xFF80609F),
    intro: '🧠 What do you think about your request?',
    task: 'Which thoughts hinder you, and which support you?'),
  GameField(n: 9,  name: 'SUBCONSCIOUSNESS',  subtitle: 'The Hidden Current',
    color: Color(0xFF46408C),
    intro: '🌀 Time for visualization.',
    task: '1. Describe your reality.  2. Close your eyes and describe the feelings.'),
  GameField(n: 10, name: 'MANIFESTATION',     subtitle: 'Reality Through Action',
    color: Color(0xFFDCBE3E),
    intro: '⚡ It\'s simple: just take action.',
    task: 'Write 10 concrete steps that can bring this into reality.'),
  GameField(n: 11, name: 'FREEDOM',           subtitle: 'Lightness · Trust · Emptiness',
    color: Color(0xFFF0E098),
    intro: 'Why is lightness so valuable?',
    task: 'Listen to yourself from within.'),
  GameField(n: 12, name: 'THE MAGICIAN',      subtitle: 'Focus · Attention · Will',
    color: Color(0xFFDCBE3E),
    intro: '🪄 A directed force is capable of literally anything. The Magician is the first cause — the creative spark.',
    task: 'Write: "I direct my power toward creating __________."'),
  GameField(n: 13, name: 'INTUITION',         subtitle: 'Calmness · Secrecy · Equilibrium',
    color: Color(0xFF6080BC),
    intro: '🔮 Quiet knowledge that guides. Here is born: "I know… but not from where."',
    task: 'Close your eyes and ask a question without words. Write: "Intuition tells me __________."'),
  GameField(n: 14, name: 'THE EMPRESS',       subtitle: 'Desire · Love · Birth of Matter',
    color: Color(0xFF2E9970),
    intro: '🌸 Life as a form of love. Here energy becomes form, body, home, care.',
    task: 'Complete: "I create __________, and it nourishes my world."'),
  GameField(n: 15, name: 'THE EMPEROR',       subtitle: 'Kindness · Aggression · Responsibility',
    color: Color(0xFFC8323A),
    intro: '🏛 Force that shapes intention. The path of responsibility and inner strength.',
    task: 'Write: "I create structure in __________, to build __________."'),
  GameField(n: 16, name: 'KNOWLEDGE',         subtitle: 'Status · Wisdom · Recognition',
    color: Color(0xFFD85838),
    intro: '📘 To live according to what you know. Knowledge is revealed through action.',
    task: 'Write: "The knowledge I am ready to live by is: __________."'),
  GameField(n: 17, name: 'CHOICE',            subtitle: 'Unconditional Love · Beauty · Sincerity',
    color: Color(0xFFD88438),
    intro: '💞 The path of the heart. You are not only choosing between options — you are choosing yourself.',
    task: 'Write: "I choose __________, because it is mine."'),
  GameField(n: 18, name: 'THE CHARIOT',       subtitle: 'Movement · Trust · Acknowledgment',
    color: Color(0xFFC8843E),
    intro: '🛡 Limitation as strength. The path of alignment with direction.',
    task: 'Write one action that requires discipline and will. Do it today.'),
  GameField(n: 19, name: 'STRENGTH',          subtitle: 'Duality · Passion · Inner Fire',
    color: Color(0xFFC8C44E),
    intro: '🦁 Softness that holds the beast. This is love that tames, not breaks.',
    task: 'Complete: "My strength lies in being able to __________ without struggle."'),
  GameField(n: 20, name: 'THE HERMIT',        subtitle: 'Calmness · Solitude · Purpose',
    color: Color(0xFF9EB85A),
    intro: '🌌 Wisdom in action. You don\'t shout — you simply shine.',
    task: 'Write 10 reasons why your desire can be beneficial to others.'),
  GameField(n: 21, name: 'THE CYCLE',         subtitle: 'Flexibility · Cyclicality · Zen',
    color: Color(0xFF7858AC),
    intro: '🎡 The wheel turns again. You don\'t control the flow, but you can choose who you are in it.',
    task: 'Complete: "I release control over __________ and allow life to move."'),
  GameField(n: 22, name: 'JUSTICE',           subtitle: 'Strictness · Justice · Decisiveness',
    color: Color(0xFF2E9970),
    intro: '⚖️ Justice is not about "good" and "bad". It is a deep proportionality where everything is in its place.',
    task: 'Complete: "My truth right now is: __________."'),
  GameField(n: 23, name: 'PAUSE',             subtitle: 'Passivity · Acceptance · Cunning',
    color: Color(0xFF1E4878),
    intro: '⏸ Pause as a strategy. Sometimes a pause is also movement.',
    task: 'Write: "I accept the limitation of __________ as a resource."'),
  GameField(n: 24, name: 'TRANSFORMATION',    subtitle: 'End · Beginning · Change',
    color: Color(0xFF389098),
    intro: '💀 Sometimes to be born, one must first die. This is not an end — it is a threshold.',
    task: 'Complete: "I release __________, to become myself."'),
  GameField(n: 25, name: 'TEMPERANCE',        subtitle: 'Spirituality · Meaning · Renunciation',
    color: Color(0xFF6080BC),
    intro: '🏵 Balance that brings things together. Focus, faith, and equilibrium.',
    task: 'Answer: "Why is my desire worthy of being realized?"'),
  GameField(n: 26, name: 'THE EGO',           subtitle: 'Dominance · Dependency · Materialism',
    color: Color(0xFF46408C),
    intro: '😈 The path of unmasking illusions. Ego is not evil — it is a survival structure.',
    task: 'Write: "One goal that no longer seems like mine: __________."\n"One intention that remains true: __________."'),
  GameField(n: 27, name: 'THE TOWER',         subtitle: 'Chaos · Collapse · Reckoning',
    color: Color(0xFFC8323A),
    intro: '🗼 A trial that destroys what is false. Only your essence will remain.',
    task: 'What do I think about my desire? And what do I feel? Is there a contradiction?'),
  GameField(n: 28, name: 'THE STAR',          subtitle: 'Distance · Lightness · Balance',
    color: Color(0xFF7858AC),
    intro: '🌟 A guiding point in the space of desire. When you follow your star — doubts recede.',
    task: 'Write: "My desire points me toward __________."'),
  GameField(n: 29, name: 'THE MOON',          subtitle: 'Empathy · Emotionality · Shadow',
    color: Color(0xFF7E2870),
    intro: '🌒 Trust in what cannot be explained. You enter the unconscious to find your true voice.',
    task: 'Complete: "I meet the shadow that __________."'),
  GameField(n: 30, name: 'THE SUN',           subtitle: 'Manifestation · Structure · Radiance',
    color: Color(0xFFD88438),
    intro: '☀️ Clarity, wholeness, maturity. Now you see, understand, and bring everything together into a structure.',
    task: 'Write: "What have I discovered about myself on this journey?"'),
  GameField(n: 31, name: 'JUDGEMENT',         subtitle: 'Strength · Overcoming · Resistance',
    color: Color(0xFFE84A28),
    intro: '🔥 Purification and awakening. All masks, evasions, half-tones — are ending.',
    task: 'Complete: "I awaken to __________."'),
  GameField(n: 32, name: 'WHOLENESS',         subtitle: 'Unity · Fullness · Completeness',
    color: Color(0xFF46408C),
    intro: '🌍 This is not just the end of the journey — it is the point where you see the whole picture. You are in your place.',
    task: 'Complete: "I acknowledge these fears, but choose to walk through them toward __________."'),
];
